# Netlify Build Configuration for a MERN Monorepo

[build]
  # This is the directory Netlify will build from
  base = "client/"
  # This command builds your React app
  command = "npm run build"
  # This is the directory that contains the built frontend
  publish = "client/dist"
  # This is where your serverless function lives
  functions = "netlify/functions"

# This rule rewrites API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200